### ISSUE TITLE
Cannot configure tool with .codacy.yml

### ISSUE THREAD

**Issue by franciscodua** [codacy/codacy-pmdjava#82]
If we have a .codacy.yml like this:
```yaml
---
engines:
 pmd:
  exclude_paths:
   - '**.sql'
```

PMD will not exclude SQL files.

**Acceptance criteria:**
- It's possible to exclude paths for PMD
